# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('IPadress', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=1)),
                ('memo', models.TextField(default='xxxx')),
                ('Gender', models.BooleanField(default=False)),
                ('CreateDat', models.DateTimeField(default='2014-10-21 12:12')),
            ],
        ),
    ]
