# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('king1', '0003_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mate1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='king1.Mate1')),
            ],
        ),
    ]
